# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-server-ext
#   namespace: monitoring
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: prometheus
#     app.kubernetes.io/instance: prometheus
#   ports:
#     - port: 9090
#       targetPort: 9090
#       nodePort: 30090
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-kube-prometheus-prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090