apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http-30081
      protocol: TCP
      port: 80         # 內部 Service port
      targetPort: 8000 # container port
      nodePort: 30081  # **指定 node port**
    - name: http-30082
      protocol: TCP
      port: 81
      targetPort: 8000
      nodePort: 30082
